### ISSUE TITLE
Snapins

### ISSUE THREAD

**Issue by mvrk69** [Vidanez/DeployVMs#12]
Hi,

Would be possible for you to reconstruct the script without using snapins? They are deprecated and not even available in PowerShell CORE.

**Comment by misteryiz** [comment]
just comment this line. https://github.com/Vidanez/DeployVMs/blob/master/DeployVM.ps1#L159
and replace with the following line : 
**Get-Module -Name VMware* -ListAvailable | Import-Module**

**Comment by mvrk69** [comment]
Hi,

Thanks, commenting out the line is enough, it seems powershell core on linux already loads the all installed modules.
