### ISSUE TITLE
Network settings are not being applied

### ISSUE THREAD

**Issue by bradley4681** [Vidanez/DeployVMs#4]
having some errors when running the script, it appears the Set-OSCustomizationNicMapping isn't working. I'm running PowerCLI 6.0 but have tried on the older versions and i'm running vCenter 5.5 and ESXi 5.5

11/20/2015 8:53:12 AM   Set-OSCustomizationNicMapping  
Required property ip is missing from data object of type CustomizationIPSettings

while parsing serialized DataObject of type vim.vm.customization.IPSettings
at line 1, column 1964

while parsing property "adapter" of static type CustomizationIPSettings

while parsing serialized DataObject of type vim.vm.customization.AdapterMapping
at line 1, column 1949

while parsing property "nicSettingMap" of static type ArrayOfCustomizationAdapterMapping

while parsing serialized DataObject of type vim.vm.customization.Specification
at line 1, column 514

while parsing property "spec" of static type CustomizationSpec

while parsing serialized DataObject of type vim.CustomizationSpecItem
at line 1, column 335

while parsing call information for method OverwriteCustomizationSpec
at line 1, column 218

while parsing SOAP body
at line 1, column 207

while parsing SOAP envelope
at line 1, column 38

while parsing HTTP request for method overwrite
on object of type vim.CustomizationSpecManager
at line 1, column 0 
Attempted to divide by zero.

**Comment by Vidanez** [comment]
Looks like the issue is somewhere else. Its missing a variable.
Do you have the csv in the right format? Did you create the CSV using the script? did you populate all variables? Are you using DHCP or Static IP? LInux or Windows?

**Comment by bradley4681** [comment]
I created it using the script, here is the file, static, windows

there isn't a field for setting the OS Customization to a previously saved one. I was using the 1.2 version from http://blog.smasterson.com/2014/05/21/deploying-multiple-vms-via-powercli-updated-v1-2/ that had a cust field but when i set it to a previously saved one i got the same types of errors

renamed to .txt in to upload
[DeployVM.txt](https://github.com/Vidanez/DeployVMs/files/40141/DeployVM.txt)

**Comment by bradley4681** [comment]
I've figured out that the script does not work with PowerCLI 6.0. I had to go back to PowerCLI 5.5 Release 2 Patch 1 build 1931983 and everything worked out without any errors.

**Comment by Vidanez** [comment]
Thats weird, I'm using it with PowerCli 6.0 without issues. Check your powershell version and plugins

**Comment by bradley4681** [comment]
PowerCLI Version
----------------
   VMware vSphere PowerCLI 6.0 Release 1 build 2548067
---------------
Component Versions
---------------
   VMWare AutoDeploy PowerCLI Component 6.0 build 2358282
   VMWare ImageBuilder PowerCLI Component 6.0 build 2358282
   VMware License PowerCLI Component 6.0 build 2315846
   VMware vSphere PowerCLI Component 6.0 build 2548068
   VMware Cloud Infrastructure Suite PowerCLI Component 6.0 build 2548068
   VMware HA PowerCLI Component 6.0 build 2510422
   VMware PowerCLI Component for Storage Management 6.0 build 2522368
   VMware VDS PowerCLI Component 6.0 build 2548068

Doesn't work on the above system but works on this system below

PowerCLI Version
----------------
   VMware vSphere PowerCLI 5.5 Release 2 Patch 1 build 1931983
---------------
Snapin Versions
---------------
   VMWare AutoDeploy PowerCLI Component 5.5 build 1890764
   VMWare ImageBuilder PowerCLI Component 5.5 build 1890764
   VMware License PowerCLI Component 5.5 build 1265954
   VMware VDS PowerCLI Component 5.5 build 1926677
   VMware vSphere PowerCLI Component 5.5 Patch 1 build 1926677

**Comment by bradley4681** [comment]
PowerCLI Version
----------------
   VMware vSphere PowerCLI 6.0 Release 1 build 2548067
---------------
Component Versions
---------------
   VMWare AutoDeploy PowerCLI Component 6.0 build 2358282
   VMWare ImageBuilder PowerCLI Component 6.0 build 2358282
   VMware License PowerCLI Component 6.0 build 2315846
   VMware vSphere PowerCLI Component 6.0 build 2548068
   VMware Cloud Infrastructure Suite PowerCLI Component 6.0 build 2548068
   VMware HA PowerCLI Component 6.0 build 2510422
   VMware PowerCLI Component for Storage Management 6.0 build 2522368
   VMware VDS PowerCLI Component 6.0 build 2548068

Doesn't work on the above system but works on this system below

PowerCLI Version
----------------
   VMware vSphere PowerCLI 5.5 Release 2 Patch 1 build 1931983
---------------
Snapin Versions
---------------
   VMWare AutoDeploy PowerCLI Component 5.5 build 1890764
   VMWare ImageBuilder PowerCLI Component 5.5 build 1890764
   VMware License PowerCLI Component 5.5 build 1265954
   VMware VDS PowerCLI Component 5.5 build 1926677
   VMware vSphere PowerCLI Component 5.5 Patch 1 build 1926677

**Comment by bradley4681** [comment]
VMware vSphere PowerCLI 6.0 Release 1 build 2548067

   VMWare AutoDeploy PowerCLI Component 6.0 build 2358282
   VMWare ImageBuilder PowerCLI Component 6.0 build 2358282
   VMware License PowerCLI Component 6.0 build 2315846
   VMware vSphere PowerCLI Component 6.0 build 2548068
   VMware Cloud Infrastructure Suite PowerCLI Component 6.0 build 2548068
   VMware HA PowerCLI Component 6.0 build 2510422
   VMware PowerCLI Component for Storage Management 6.0 build 2522368
   VMware VDS PowerCLI Component 6.0 build 2548068

PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

---

## Doesn't work on the above system but works on this system below

   VMware vSphere PowerCLI 5.5 Release 2 Patch 1 build 1931983

   VMWare AutoDeploy PowerCLI Component 5.5 build 1890764
   VMWare ImageBuilder PowerCLI Component 5.5 build 1890764
   VMware License PowerCLI Component 5.5 build 1265954
   VMware VDS PowerCLI Component 5.5 build 1926677
   VMware vSphere PowerCLI Component 5.5 Patch 1 build 1926677

WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0}
SerializationVersion           1.1.0.1
BuildVersion                   6.2.9200.16481
PSVersion                      3.0
CLRVersion                     4.0.30319.1026
PSRemotingProtocolVersion      2.2

**Comment by RezaAmbler** [comment]
Ensure you're using the 32 bit version of PowerCLI when making use of the OSCustomization cmdlets
