### ISSUE TITLE
Throttle Deployments

### ISSUE THREAD

**Issue by bradley4681** [Vidanez/DeployVMs#7]
Is there a way to limit the total concurrent deployments? I'm deploying 400 VMs and I've been creating files with just 5 at a time because I tried to deploy using a file containing 100 and all 100 kicked off.

**Comment by Vidanez** [comment]
That's controlled by the vcenter itself, depending on the resources available, it put the order waiting on queue. Usually you will see no more than 10 deployment progressing the bar lines, the rest would be waiting for reources

**Comment by bradley4681** [comment]
Yeah I see that its limited to 10 by VMware but it appears to deploy faster if only 5 or actually running at a time from a single template.

**Comment by Vidanez** [comment]
You can include a loop to call for more csv files :)
